declare namespace hook {
  // ---------------------------------------------------------------------------
  // SField codes (lowered to i32 constants at compile time)
  // ---------------------------------------------------------------------------
  export const sfInvalid: I32
  export const sfGeneric: I32
  export const sfCloseResolution: I32
  export const sfMethod: I32
  export const sfTransactionResult: I32
  export const sfScale: I32
  export const sfAssetScale: I32
  export const sfTickSize: I32
  export const sfUNLModifyDisabling: I32
  export const sfHookResult: I32
  export const sfWasLockingChainSend: I32
  export const sfLedgerEntryType: I32
  export const sfTransactionType: I32
  export const sfSignerWeight: I32
  export const sfTransferFee: I32
  export const sfTradingFee: I32
  export const sfDiscountedFee: I32
  export const sfVersion: I32
  export const sfHookStateChangeCount: I32
  export const sfHookEmitCount: I32
  export const sfHookExecutionIndex: I32
  export const sfHookApiVersion: I32
  export const sfHookStateScale: I32
  export const sfLedgerFixType: I32
  export const sfNetworkID: I32
  export const sfFlags: I32
  export const sfSourceTag: I32
  export const sfSequence: I32
  export const sfPreviousTxnLgrSeq: I32
  export const sfLedgerSequence: I32
  export const sfCloseTime: I32
  export const sfParentCloseTime: I32
  export const sfSigningTime: I32
  export const sfExpiration: I32
  export const sfTransferRate: I32
  export const sfWalletSize: I32
  export const sfOwnerCount: I32
  export const sfDestinationTag: I32
  export const sfLastUpdateTime: I32
  export const sfHighQualityIn: I32
  export const sfHighQualityOut: I32
  export const sfLowQualityIn: I32
  export const sfLowQualityOut: I32
  export const sfQualityIn: I32
  export const sfQualityOut: I32
  export const sfStampEscrow: I32
  export const sfBondAmount: I32
  export const sfLoadFee: I32
  export const sfOfferSequence: I32
  export const sfFirstLedgerSequence: I32
  export const sfLastLedgerSequence: I32
  export const sfTransactionIndex: I32
  export const sfOperationLimit: I32
  export const sfReferenceFeeUnits: I32
  export const sfReserveBase: I32
  export const sfReserveIncrement: I32
  export const sfSetFlag: I32
  export const sfClearFlag: I32
  export const sfSignerQuorum: I32
  export const sfCancelAfter: I32
  export const sfFinishAfter: I32
  export const sfSignerListID: I32
  export const sfSettleDelay: I32
  export const sfTicketCount: I32
  export const sfTicketSequence: I32
  export const sfNFTokenTaxon: I32
  export const sfMintedNFTokens: I32
  export const sfBurnedNFTokens: I32
  export const sfHookStateCount: I32
  export const sfEmitGeneration: I32
  export const sfVoteWeight: I32
  export const sfLockCount: I32
  export const sfFirstNFTokenSequence: I32
  export const sfOracleDocumentID: I32
  export const sfStartTime: I32
  export const sfRepeatCount: I32
  export const sfDelaySeconds: I32
  export const sfXahauActivationLgrSeq: I32
  export const sfImportSequence: I32
  export const sfRewardTime: I32
  export const sfRewardLgrFirst: I32
  export const sfRewardLgrLast: I32
  export const sfIndexNext: I32
  export const sfIndexPrevious: I32
  export const sfBookNode: I32
  export const sfOwnerNode: I32
  export const sfBaseFee: I32
  export const sfExchangeRate: I32
  export const sfLowNode: I32
  export const sfHighNode: I32
  export const sfDestinationNode: I32
  export const sfCookie: I32
  export const sfServerVersion: I32
  export const sfNFTokenOfferNode: I32
  export const sfEmitBurden: I32
  export const sfHookInstructionCount: I32
  export const sfHookReturnCode: I32
  export const sfReferenceCount: I32
  export const sfXChainClaimID: I32
  export const sfXChainAccountCreateCount: I32
  export const sfXChainAccountClaimCount: I32
  export const sfAssetPrice: I32
  export const sfMaximumAmount: I32
  export const sfOutstandingAmount: I32
  export const sfMPTAmount: I32
  export const sfIssuerNode: I32
  export const sfSubjectNode: I32
  export const sfTouchCount: I32
  export const sfAccountIndex: I32
  export const sfAccountCount: I32
  export const sfRewardAccumulator: I32
  export const sfEmailHash: I32
  export const sfTakerPaysCurrency: I32
  export const sfTakerPaysIssuer: I32
  export const sfTakerGetsCurrency: I32
  export const sfTakerGetsIssuer: I32
  export const sfMPTokenIssuanceID: I32
  export const sfLedgerHash: I32
  export const sfParentHash: I32
  export const sfTransactionHash: I32
  export const sfAccountHash: I32
  export const sfPreviousTxnID: I32
  export const sfLedgerIndex: I32
  export const sfWalletLocator: I32
  export const sfRootIndex: I32
  export const sfAccountTxnID: I32
  export const sfNFTokenID: I32
  export const sfEmitParentTxnID: I32
  export const sfEmitNonce: I32
  export const sfEmitHookHash: I32
  export const sfObjectID: I32
  export const sfAMMID: I32
  export const sfBookDirectory: I32
  export const sfInvoiceID: I32
  export const sfNickname: I32
  export const sfAmendment: I32
  export const sfHookOn: I32
  export const sfDigest: I32
  export const sfChannel: I32
  export const sfConsensusHash: I32
  export const sfCheckID: I32
  export const sfValidatedHash: I32
  export const sfPreviousPageMin: I32
  export const sfNextPageMin: I32
  export const sfNFTokenBuyOffer: I32
  export const sfNFTokenSellOffer: I32
  export const sfHookStateKey: I32
  export const sfHookHash: I32
  export const sfHookNamespace: I32
  export const sfHookSetTxnID: I32
  export const sfOfferID: I32
  export const sfEscrowID: I32
  export const sfURITokenID: I32
  export const sfDomainID: I32
  export const sfHookOnOutgoing: I32
  export const sfHookOnIncoming: I32
  export const sfCron: I32
  export const sfHookCanEmit: I32
  export const sfEmittedTxnID: I32
  export const sfGovernanceMarks: I32
  export const sfGovernanceFlags: I32
  export const sfNumber: I32
  export const sfAmount: I32
  export const sfBalance: I32
  export const sfLimitAmount: I32
  export const sfTakerPays: I32
  export const sfTakerGets: I32
  export const sfLowLimit: I32
  export const sfHighLimit: I32
  export const sfFee: I32
  export const sfSendMax: I32
  export const sfDeliverMin: I32
  export const sfAmount2: I32
  export const sfBidMin: I32
  export const sfBidMax: I32
  export const sfMinimumOffer: I32
  export const sfRippleEscrow: I32
  export const sfDeliveredAmount: I32
  export const sfNFTokenBrokerFee: I32
  export const sfHookCallbackFee: I32
  export const sfLockedBalance: I32
  export const sfBaseFeeDrops: I32
  export const sfReserveBaseDrops: I32
  export const sfReserveIncrementDrops: I32
  export const sfLPTokenOut: I32
  export const sfLPTokenIn: I32
  export const sfEPrice: I32
  export const sfPrice: I32
  export const sfSignatureReward: I32
  export const sfMinAccountCreateAmount: I32
  export const sfLPTokenBalance: I32
  export const sfTrustLineRewardAccumulator: I32
  export const sfPublicKey: I32
  export const sfMessageKey: I32
  export const sfSigningPubKey: I32
  export const sfTxnSignature: I32
  export const sfURI: I32
  export const sfSignature: I32
  export const sfDomain: I32
  export const sfFundCode: I32
  export const sfRemoveCode: I32
  export const sfExpireCode: I32
  export const sfCreateCode: I32
  export const sfMemoType: I32
  export const sfMemoData: I32
  export const sfMemoFormat: I32
  export const sfFulfillment: I32
  export const sfCondition: I32
  export const sfMasterSignature: I32
  export const sfUNLModifyValidator: I32
  export const sfValidatorToDisable: I32
  export const sfValidatorToReEnable: I32
  export const sfHookStateData: I32
  export const sfHookReturnString: I32
  export const sfHookParameterName: I32
  export const sfHookParameterValue: I32
  export const sfBlob: I32
  export const sfDIDDocument: I32
  export const sfData: I32
  export const sfAssetClass: I32
  export const sfProvider: I32
  export const sfMPTokenMetadata: I32
  export const sfCredentialType: I32
  export const sfRemarkValue: I32
  export const sfRemarkName: I32
  export const sfAccount: I32
  export const sfOwner: I32
  export const sfDestination: I32
  export const sfIssuer: I32
  export const sfAuthorize: I32
  export const sfUnauthorize: I32
  export const sfRegularKey: I32
  export const sfNFTokenMinter: I32
  export const sfEmitCallback: I32
  export const sfHolder: I32
  export const sfHookAccount: I32
  export const sfOtherChainSource: I32
  export const sfOtherChainDestination: I32
  export const sfAttestationSignerAccount: I32
  export const sfAttestationRewardAccount: I32
  export const sfLockingChainDoor: I32
  export const sfIssuingChainDoor: I32
  export const sfSubject: I32
  export const sfInform: I32
  export const sfIndexes: I32
  export const sfHashes: I32
  export const sfAmendments: I32
  export const sfNFTokenOffers: I32
  export const sfHookNamespaces: I32
  export const sfCredentialIDs: I32
  export const sfURITokenIDs: I32
  export const sfPaths: I32
  export const sfBaseAsset: I32
  export const sfQuoteAsset: I32
  export const sfLockingChainIssue: I32
  export const sfIssuingChainIssue: I32
  export const sfAsset: I32
  export const sfAsset2: I32
  export const sfClaimCurrency: I32
  export const sfXChainBridge: I32
  export const sfTransactionMetaData: I32
  export const sfCreatedNode: I32
  export const sfDeletedNode: I32
  export const sfModifiedNode: I32
  export const sfPreviousFields: I32
  export const sfFinalFields: I32
  export const sfNewFields: I32
  export const sfTemplateEntry: I32
  export const sfMemo: I32
  export const sfSignerEntry: I32
  export const sfNFToken: I32
  export const sfEmitDetails: I32
  export const sfHook: I32
  export const sfSigner: I32
  export const sfMajority: I32
  export const sfDisabledValidator: I32
  export const sfEmittedTxn: I32
  export const sfHookExecution: I32
  export const sfHookParameter: I32
  export const sfHookGrant: I32
  export const sfVoteEntry: I32
  export const sfAuctionSlot: I32
  export const sfAuthAccount: I32
  export const sfXChainClaimProofSig: I32
  export const sfXChainCreateAccountProofSig: I32
  export const sfXChainClaimAttestationCollectionElement: I32
  export const sfXChainCreateAccountAttestationCollectionElement: I32
  export const sfPriceData: I32
  export const sfCredential: I32
  export const sfAmountEntry: I32
  export const sfMintURIToken: I32
  export const sfHookEmission: I32
  export const sfImportVLKey: I32
  export const sfActiveValidator: I32
  export const sfGenesisMint: I32
  export const sfRemark: I32
  export const sfHighReward: I32
  export const sfLowReward: I32
  export const sfSigners: I32
  export const sfSignerEntries: I32
  export const sfTemplate: I32
  export const sfNecessary: I32
  export const sfSufficient: I32
  export const sfAffectedNodes: I32
  export const sfMemos: I32
  export const sfNFTokens: I32
  export const sfHooks: I32
  export const sfVoteSlots: I32
  export const sfMajorities: I32
  export const sfDisabledValidators: I32
  export const sfHookExecutions: I32
  export const sfHookParameters: I32
  export const sfHookGrants: I32
  export const sfXChainClaimAttestations: I32
  export const sfXChainCreateAccountAttestations: I32
  export const sfPriceDataSeries: I32
  export const sfAuthAccounts: I32
  export const sfAuthorizeCredentials: I32
  export const sfUnauthorizeCredentials: I32
  export const sfAcceptedCredentials: I32
  export const sfAmounts: I32
  export const sfHookEmissions: I32
  export const sfImportVLKeys: I32
  export const sfActiveValidators: I32
  export const sfGenesisMints: I32
  export const sfRemarks: I32
}
